# Default values for filebeat-wes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/beats/filebeat
  tag: 6.7.1
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

filebeat:
  LOG_FILE_PATHS: "/host-var-log/*log,/host-var-log/*/*log"
  LOGSTASH_HOST: "logstash-wes:5044"
  LOCATION: "weshouse"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


filebeatConfig:
  filebeat.yml: |-
    filebeat.config:
      modules:
        path: "${path.config}/modules.d/*.yml"
        # Reload module configs as they change:
        reload.enabled: "false"
      #inputs:
      #  # Mounted `filebeat-inputs` configmap:
      #  path: ${path.config}/inputs.d/*.yml
      #  # Reload inputs configs as they change:
      #  reload.enabled: false
      #
    # To enable hints based autodiscover, remove `filebeat.config.inputs`
    # configuration and uncomment this:
    filebeat.autodiscover:
      providers:
        - type: "kubernetes"
          hints.enabled: "true"
    output.logstash:
      hosts: ['${LOGSTASH_HOST}']

filebeatInputs:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
