apiVersion: v1
kind: Service
metadata:
  name: es-loadbalancer-service
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: http-lb
    protocol: TCP
    port: {{ .Values.elasticsearch.httpPort }}
  - name: transport-lb
    protocol: TCP
    port: {{ .Values.elasticsearch.transportPort }}
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "uname" . }}"
  type: LoadBalancer
  loadBalancerIP: 10.2.2.231
