# Deploys prowlarr
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex-wes.fullname" . }}-prowlarr
  labels:
    {{- include "plex-wes.labels" . | nindent 4 }}
    app.kubernetes.io/extraService: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "plex-wes.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/extraService: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "plex-wes.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/extraService: prowlarr
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex-wes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-prowlarr
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.prowlarr.repository }}:{{ .Values.image.prowlarr.tag | default .Chart.AppVersion }}"
          env:
            - name: PUID
              value: "{{ .Values.allServarr.puid }}"
            - name: PGID
              value: "{{ .Values.allServarr.pgid }}"
            - name: TZ
              value: "{{ .Values.allServarr.tz }}"
          imagePullPolicy: Always
          ports:
            - name: prowlarr-web
              containerPort: {{ .Values.prowlarr.service.port }}
              protocol: TCP
          volumeMounts:
          - name: plex-data
            mountPath: /data
          - name: servarr-data
            subPath: prowlarr-config
            mountPath: /config
          - name: servarr-data
            subPath: qbittorrent-config/downloads
            mountPath: /app/qBittorrent/downloads
          startupProbe:
            httpGet:
              path: /
              port: prowlarr-web
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: prowlarr-web
          readinessProbe:
            httpGet:
              path: /
              port: prowlarr-web
          resources:
            {{- toYaml .Values.prowlarr.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: plex-data
        persistentVolumeClaim:
          claimName: {{ .Values.plex.persistence.plexData }}
      - name: servarr-data
        persistentVolumeClaim:
          claimName: {{ .Values.plex.persistence.servarrData }}
