apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex-wes.fullname" . }}-radarr
  labels:
    {{- include "plex-wes.labels" . | nindent 4 }}
    app.kubernetes.io/extraService: radarr
spec:
  type: {{ .Values.radarr.service.type }} 
  ports:
    - port: {{ .Values.radarr.service.port }}
      targetPort: {{ .Values.radarr.service.port }}
      protocol: TCP
      name: radarr
  selector:
    {{- include "plex-wes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/extraService: radarr
