apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex-wes.fullname" . }}-watchstate
  labels:
    {{- include "plex-wes.labels" . | nindent 4 }}
    app.kubernetes.io/extraService: watchstate
spec:
  type: {{ .Values.watchstate.service.type }}
  ports:
    - port: {{ .Values.watchstate.service.port }}
      targetPort: {{ .Values.watchstate.service.port }}
      protocol: TCP
      name: watchstate
  selector:
    {{- include "plex-wes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/extraService: watchstate
