apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  annotations:
    # Make sure CRDs are installed first
    # May have to run helm install twice?
    # This hook doesn't seem to be working
    # "helm.sh/hook": post-install
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wes@elastiscale.net
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: nginx-wes
