apiVersion: v1
name: filebeat
version: 1.3.0
appVersion: 5.6.2
description: Forwards log file data to logstash
keywords:
- logging
icon: "https://amsterdam.luminis.eu/wp-content/uploads/2016/02/elastic-beats-fw.png"
sources:
- https://github.com/wesparish/docker-filebeat
maintainers:
- name: wes
  email: wes@elastiscale.net

