# Default values for tsd-ml-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  ml_api:
    repository: thespaghettidetective/ml_api
    tag: 0.95
    pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

ml_api:
  gpu:
    enabled: true
    gpus_per_pod: 1

service:
  type: NodePort
  port: 3334

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-wes
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - ml_api
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
  paths:
    - /
  hosts:
    - ml-api.elastiscale.net
  tls:
    - secretName: ml-api-elastiscale.net
      hosts:
        - ml-api.elastiscale.net

nodeSelector: {}
  #  ceph-client: "true"

tolerations: []

affinity: {}
