sonatype-nexus:
  nexus:
    nodeSelector:
      ceph-client: "true"

  nexusProxy:
    env:
      nexusDockerHost: nexus.elastiscale.net
      nexusHttpHost: nexus.elastiscale.net

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-wes
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    paths:
      - /
    hosts:
      - nexus.elastiscale.net
    tls:
      enabled: true
      secretName: nexus-elastiscale.net

  persistence:
    existingClaim: nexus-data

  resources:
    requests:
      cpu: 250m
      memory: 4800Mi
