sonatype-nexus:
  nexus:
    imageName: wesparish/nexus-repository-apt
    imageTag: 3.15.2
    imagePullPolicy: Always
    nodeSelector:
      ceph-client: "true"
    dockerPort: 5010

  nexusProxy:
    env:
      nexusDockerHost: nexus.elastiscale.net
      nexusHttpHost: nexus.elastiscale.net

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-wes
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    paths:
      - /
    hosts:
      - nexus.elastiscale.net
    tls:
      enabled: true
      secretName: nexus-elastiscale.net

  persistence:
    existingClaim: nexus-wes-sonatype-nexus-data

  resources:
    requests:
      cpu: 250m
      memory: 4800Mi

nginx-ingress:
  controller:
    ingressClass: nginx-nexus
    service:
      type: LoadBalancer
      loadBalanerIP: 172.16.1.221
      enableHttps: 5010
