version: '2'
services:
  claymore-amd:
    start_on_create: false
  claymore-amd-scalable:
    start_on_create: false
catalog:
  name: Claymore AMD
  version: 11.5-1
  description: Claymore AMD
  questions:
    - variable: WALLET_ADDRESS
      label: Wallet address
      default: 0x559db2865e1f099d63037c3ae4a6c8cc1106c819
      type: string
    - variable: HOSTS
      label: Pool Hosts 
      default: eth-us-east1.nanopool.org:9999:x:0:0 eth-us-west1.nanopool.org:9999:x:0:0
      type: string
    - variable: CLAYMORE_OPTS
      label: Extra Claymore Options
      default: -r 1 -nofee -mode 1
      type: string
    - variable: CLAYMORE_SCALABLE_LABEL
      label: Scheduling label for claymore_amd_scalable service, miner=<>
      default: claymore_scalable
      type: string
    - variable: CLAYMORE_LABEL
      label: Scheduling label for claymore_amd_scalable service, miner=<>
      default: claymore
      type: string

