apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "friendica-wes.fullname" . }}
  labels:
    {{- include "friendica-wes.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "friendica-wes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "friendica-wes.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "friendica-wes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-db
          image: "docker.io/bitnami/mariadb:11.1.3-debian-11-r0"
          env:
            - name: DB_HOST
              value: friendica-mariadb
            - name: DB_USER
              value: friendica
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: mariadb-password
          args:
          - /bin/sh
          - -c
          - |
            set -x
            echo -n "Waiting for mariadb to start..."
            while ! mariadb-admin \
              --connect-timeout=1 \
              ping \
              -u${DB_USER} \
              --password=${DB_PASS} \
              -h${DB_HOST} > /dev/null ; do
              sleep 1
              echo "."
            done

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FRIENDICA_URL
              value: {{ .Values.friendica.url | quote }}
            - name: FRIENDICA_ADMIN_MAIL
              value: {{ .Values.friendica.adminEmail | quote }}
            - name: MYSQL_USER
              value: "friendica"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: mariadb-password
            - name: MYSQL_DATABASE
              value: "friendica"
            - name: MYSQL_HOST
              value: "friendica-mariadb"
            - name: FRIENDICA_TZ
              value: "America/Chicago"
            - name: FRIENDICA_SITENAME
              value: "Friendica"
            - name: REDIS_HOST
              value: "friendica-redis-master"
            - name: MAILNAME
              value: "wes@elastiscale.net"
            - name: SMTP
              value: "mailu-postfix.mailu"
            - name: SMTP_PORT
              value: "25"
            - name: SMTP_DOMAIN
              value: "elastiscale.net"
            - name: SMTP_FROM
              value: "friendica"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # volumeMounts:
          # - name: friendica-data
          #   mountPath: /var/www/html
          #   {{- if .Values.friendica.persistence.subPath }}
          #   subPath: {{ .Values.friendica.persistence.subPath }}
          #   {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: friendica-data
        persistentVolumeClaim:
          claimName: {{ .Values.friendica.persistence.existingClaim }}
