# Default values for games-on-whales-wes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

games-on-whales:
  service:
    # -- Enable and configure TCP service settings for the chart under this key.
    # @default -- See values.yaml
    main: #{}
      type: LoadBalancer
      loadBalancerIP: 172.16.1.240
      annotations:
        metallb.universe.tf/allow-shared-ip: "sharing-key"

    # -- Enable and configure UDP service settings for the chart under this key.
    # @default -- See values.yaml
    udp: #{}
      type: LoadBalancer
      loadBalancerIP: 172.16.1.240
      annotations:
        metallb.universe.tf/allow-shared-ip: "sharing-key"

  persistence:
    home:
      enabled: true
      # type: pvc
      # existingClaim: "games-on-whales-data"
      type: hostPath
      hostPath: /var/data/games-on-whales
      mountPath: /home/retro

  # Note: This requests a GPU for each pod, minimum 3
  graphic_resources:
   nvidia.com/gpu: 1

  retroarch:
    enabled: false
  # firefox:
  #   enabled: false

  # nodeSelector:
  #   kubernetes.io/hostname: w-dock9

