---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-new
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  cephfs:
    monitors:
    - 172.16.1.109
    - 172.16.1.107
    - 172.16.1.197
    path: k8s-volumes/mailu/
    secretRef:
      name: ceph-secret
      namespace: kube-system
    user: admin
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-new
  namespace: mailu-new
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: mailu-new


