# Default values for shinobi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nexus-jamie-docker.elastiscale.net/migoller/shinobidocker
  tag: ng #latest # microservice-debian
  pullPolicy: IfNotPresent
  mariadb:
    repository: nexus-jamie-docker.elastiscale.net/mariadb
    tag: "10.3"

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  annotations: #{}
    kubernetes.io/ingress.class: nginx-wes
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - shinobi-jamie.elastiscale.net
  tls: #[]
    - secretName: shinobi-jamie-elastiscale.net
      hosts:
        - shinobi-jamie.elastiscale.net

resources: {}
 # limits:
 #   nvidia.com/gpu: 1
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  ceph-client: "true"

tolerations: []

affinity: {}

shinobi:
  admin:
    password: set-in-rancher-questions
  cronKey: set-in-rancher-questions

mariadb:
  rootUser:
    password: set-in-rancher-questions
    forcePassword: true
  db:
    user: shinobi
    password: set-in-rancher-questions
    forcePassword: true
  master:
    nodeSelector:
      ceph-client: "true"
    persistence:
      enabled: true
      existingClaim: shinobi-db
  slave:
    replicas: 0
