apiVersion: v1
kind: Service
metadata:
  name: {{ include "tesla-wall-connector-exporter-wes.fullname" . }}
  labels:
    {{- include "tesla-wall-connector-exporter-wes.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.service.type }}
  type: externalName
  externalName: {{ .Values.service.externalName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tesla-wall-connector-exporter-wes.selectorLabels" . | nindent 4 }}
