# Default values for duplicacy-wes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  duplicacyWeb:
    repository: saspus/duplicacy-web
    tag: latest
  duplicacyCLI:
    repository: wesparish/docker-duplicacycli
    tag: ubuntu-18.04-2.7.2
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3875

duplicacy:
  auth: wes:$apr1$sLLQK9lR$NBDb6NtuzOC6sTHxZ1tuC0
  persistence:
    duplicacyConfigClaim: duplicacy-config
    duplicacyStorageClaim: duplicacy-storage

  backups:
    - name: raid5kdrive-home
      persistence:
        source:
          claim: duplicacy-backup-raid5kdrive
          subPath: home
        storage:
          claim: duplicacy-backup-storage
      cron: '@daily'
      args: [ 'backup', '-threads', '4', '-stats' ]
    # - name: raid5kdrive-home-remote
    #   persistence:
    #     source:
    #       claim: duplicacy-backup-raid5kdrive
    #       subPath: home
    #     storage:
    #       # Chose either override (specify URL) or claim (PVC)
    #       override: "minio://region@minio-jamie.elastiscale.net/wes-backup-2/raid5kdrive-home"
    #       secrets:
    #         # For S3, create a secret with keys
    #         # duplicacy_s3_id and duplicacy_s3_secret
    #         s3: minio-remote-keys-omv
    #   cron: '@daily'
    #   args: [ 'backup', '-threads', '4', '-stats' ]
    - name: raid5kdrive
      persistence:
        source:
          claim: duplicacy-backup-raid5kdrive
        storage:
          claim: duplicacy-backup-storage
      cron: '@weekly'
      args: [ 'backup', '-threads', '4', '-stats' ]
      filters: |
        -VMWARE_VMS/
    # - name: raid5kdrive-remote
    #   persistence:
    #     source:
    #       claim: duplicacy-backup-raid5kdrive
    #     storage:
    #       # Chose either override (specify URL) or claim (PVC)
    #       override: "minio://region@minio-jamie.elastiscale.net/wes-backup-2/raid5kdrive"
    #       secrets:
    #         # For S3, create a secret with keys
    #         # duplicacy_s3_id and duplicacy_s3_secret
    #         s3: minio-remote-keys-omv
    #   cron: '@weekly'
    #   args: [ 'backup', '-threads', '4', '-stats' ]
    #   filters: |
    #     -VMWARE_VMS/
    - name: cephfs-remote
      persistence:
        source:
          claim: duplicacy-backup-cephfs
        storage:
          # Chose either override (specify URL) or claim (PVC)
          override: "minio://region@minio-jamie.elastiscale.net/wes-backup-1/cephfs"
          secrets:
            # For S3, create a secret with keys
            # duplicacy_s3_id and duplicacy_s3_secret
            s3: minio-remote-keys-ubuntu
      cron: '@daily'
      command: ['tail', '-f', '/etc/hosts']
      # args: [ 'backup', '-threads', '4', '-stats' ]
      filters: |
        +k8s-volumes/minio-data/*
        +k8s-volumes/vaultwarden-data/*
        +k8s-volumes/deluge-config/*
        +k8s-volumes/duplicacy-config/*
        +k8s-volumes/keycloak-data/*
        +k8s-volumes/node-red-data/*
        +k8s-volumes/onlyoffice-data/*
        +k8s-volumes/homeassistant-config/*
        +k8s-volumes/owncloud-mariadb-pvc/*
        +k8s-volumes/netmaker-data/*
        +k8s-volumes/code-server/*
        +k8s-volumes/homeassistant-db/*
        +k8s-volumes/virt-manager-data/*
        +k8s-volumes/mongodb-data/*
        +k8s-volumes/frigate-data/*
        +k8s-volumes/plexpy-data/*
        +k8s-volumes/rocketchat-data/*
        +k8s-volumes/pihole-data/*
        +k8s-volumes/asterisk-pvc/*
        +k8s-volumes/svn-data/*
        +k8s-volumes/rocketchat-backup/*
        +k8s-volumes/nexus-data/*
        +k8s-volumes/servarr-data/*
        +k8s-volumes/mailu/*
        +k8s-volumes/immich-data/*
        +k8s-volumes/owncloud-data-pvc/*
        +k8s-volumes/
        +backups/*
        +backups/
        -*

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-wes
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - Duplicacy
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  paths:
    - /
  hosts:
    - duplicacy.elastiscale.net
  tls:
    - secretName: duplicacy-elastiscale.net
      hosts:
        - duplicacy.elastiscale.net

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  duplicacy: "true"

tolerations: []

affinity: {}
