---
kibana:
  image: "nexus-jamie-docker.elastiscale.net/kibana/kibana"
  imageTag: "7.2.0"
  elasticsearchHosts: "http://elasticsearch.jamiehouse:9200"
  nodeSelector:
    node-role.kubernetes.io/controlplane: "true"
  service:
    type: NodePort
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-wes
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required - Kibana
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-type: basic
    path: /
    hosts:
      - kibana-jamie.elastiscale.net
    tls:
      - secretName: kibana-jamie-elastiscale.net
        hosts:
          - kibana-jamie.elastiscale.net


