apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex-wes.fullname" . }}-seerr
  labels:
    {{- include "plex-wes.labels" . | nindent 4 }}
    app.kubernetes.io/extraService: seerr
spec:
  type: {{ .Values.seerr.service.type }}
  ports:
    - port: {{ .Values.seerr.service.port }}
      targetPort: {{ .Values.seerr.service.port }}
      protocol: TCP
      name: seerr
  selector:
    {{- include "plex-wes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/extraService: seerr
