apiVersion: v1
kind: Service
metadata:
  name: kube-plex-wes-plexpy-svc
  labels:
    app.kubernetes.io/name: kube-plex-wes-plexpy-svc
    helm.sh/chart: kube-plex-wes
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: plexpy
  selector:
    app.kubernetes.io/name: kube-plex-wes-plexpy
    app.kubernetes.io/instance: {{ .Release.Name }}
