apiVersion: v1
kind: Service
metadata:
  name: kube-plex-loadbalancer-svc
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: plex
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app: kube-plex
  type: LoadBalancer
  loadBalancerIP: 172.16.1.220
