kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx-wes
        kubernetes.io/tls-acme: "true"
      hosts:
        - grafana.elastiscale.net
      paths:
        - /
      pathType: ImplementationSpecific
      tls:
        - secretName: grafana.elastiscale.net-tls
          hosts:
          - grafana.elastiscale.net
    persistence:
      enabled: true
      existingClaim: kube-prometheus-stack-data
      subPath: grafana

  prometheus:
    prometheusSpec:
      storageSpec:
        # emptyDir: {}
        volumeClaimTemplate:
          spec:
            # Name of the PV you created beforehand
            volumeName: kube-prometheus-stack-prometheus-data
            accessModes: ["ReadWriteMany"]
            # StorageClass should match your existing PV's storage class
            storageClassName: ""
            resources:
              requests:
                # Size below should match your existing PV's size
                storage: 50Gi
      # Find all service monitors and pod monitors
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}
      scrapeInterval: "30s"
      evaluationInterval: "30s"