apiVersion: v1
appVersion: "1.21.0"
description: A Helm chart for Kubernetes
name: nginx-ingress-wes
version: 0.2.0

# helm repo add nginx-stable https://helm.nginx.com/stable
dependencies:
  - name: nginx-ingress
    version: "0.10.3"
    repository: "@nginx-stable"
