# Default values for nginx-ingress-wes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress-nginx:
  controller:
    ingressClass: nginx-wes
    service:
      type: LoadBalancer
      loadBalancerIP: 172.16.1.223
      annotations:
        metallb.universe.tf/address-pool: default
    kind: DaemonSet
    nodeSelector:
      ingress: "true"
