mosquitto-wes:
  mosquitto:
    service:
      loadBalancerIP: 192.168.4.11

    config: |
      persistence false
      log_dest stdout
      listener 1883
      allow_anonymous true
      listener 9090
      allow_anonymous true
      protocol websockets

    persistence:
      enabled: false

    nodeSelector: null