# Default values for minio-wes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minio:
  service:
    type: LoadBalancer
    loadBalancerIP: 10.2.2.237
# Private only, no ingress for now
#  ingress:
#    enabled: true
#    ingressClassName: nginx-wes
#    annotations:
#     kubernetes.io/ingress.class: nginx-wes
#      kubernetes.io/tls-acme: "true"
#  apiIngress:
#    enabled: true
#    ingressClassName: nginx-wes
#    annotations:
#     kubernetes.io/ingress.class: nginx-wes
#      kubernetes.io/tls-acme: "true"
  persistence:
    enabled: true
    existingClaim: minio-data
  volumePermissions:
    enabled: true
  extraEnvVars:
    - name: MINIO_SERVER_URL
      value: http://10.2.2.237:9000
