apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: octopi
  annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required - OctoPi
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/proxy-body-size: 200m
spec:
  rules:
    - host: octopi.elastiscale.net
      http:
        paths:
          - path: /
            backend:
              serviceName: octopi
              servicePort: 80
  tls:
    - hosts:
      - octopi.elastiscale.net
      secretName: octopi-elastiscale.net
