{{- range .Values.backups }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "borg-backup-{{ .name }}"
spec:
  suspend: {{ .suspend | default "false" }}
  # how many completed jobs should be kept
  successfulJobsHistoryLimit: 3
  # how many failed jobs should be kept
  failedJobsHistoryLimit: 3
  # Choose Forbid if you don't want concurrent executions of your Job
  concurrencyPolicy: Forbid
  # The amount of time that Kubernetes can miss and still start a job.
  # If Kubernetes missed too many job starts (100)
  # then Kubernetes logs an error and doesn’t start any future jobs.
  startingDeadlineSeconds: 300
  schedule: "{{ .cron }}"
  jobTemplate:
    spec:
      # How many pods will be instantiated at once
      parallelism: 1
      # How many containers of the job are instantiated one after the other
      # (sequentially) inside the pod
      completions: 1
      # # Maximum pod restarts in case of failure
      backoffLimit: 1
      template:
        spec:
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: borg-backup-{{ .name }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            {{- if .command }}
            command:
            {{- toYaml .command | nindent 12 }}
            {{- end }}
            {{- if .args }}
            args:
            {{- toYaml .args | nindent 12 }}
            {{- end }}
            workingDir: "/source"
            env:
              {{- if .persistence.secrets.borg_passphrase }}
              - name: BORG_PASSPHRASE
                valueFrom:
                  secretKeyRef:
                    name: {{ .persistence.secrets.borg_passphrase }}
                    key: borg-passphrase
              {{- end }}
              {{- if .persistence.borgBaseDir }}
                {{- if .persistence.borgBaseDir.claim }}
              - name: BORG_BASE_DIR
                value: "/borg-base-dir"
                {{- end }}
              {{- end }}
              - name: BORG_RELOCATED_REPO_ACCESS_IS_OK
                value: "yes"
            volumeMounts:
            - name: source
              mountPath: "/source"
              readOnly: true
              {{- if .persistence.source.subPath }}
              subPath: "{{ .persistence.source.subPath }}"
              {{- end }}
            - name: borgmatic-config
              mountPath: "/borgmatic-config.yaml"
              subPath: "borgmatic-config.yaml"
            {{- if .persistence.secrets.ssh_key }}
            - name: ssh-key
              mountPath: "/root/id_rsa"
              subPath: "id_rsa"
            {{- end }}
            {{- if .persistence.borgBaseDir }}
              {{- if .persistence.borgBaseDir.claim }}
            - name: borg-base-dir
              mountPath: "/borg-base-dir"
              {{- if .persistence.borgBaseDir.subPath }}
              subPath: "{{ .persistence.borgBaseDir.subPath }}"
              {{- end }}
              {{- end }}
            {{- end }}
            lifecycle:
              postStart:
                exec:
                  command:
                  - /bin/sh
                  - -c
                  - |
                    mkdir -p /root/.ssh
                    chmod 0700 /root/.ssh
                    cp /root/id_rsa /root/.ssh/id_rsa
                    chmod 0400 /root/.ssh/id_rsa
                    mkdir -p /etc/borgmatic/
                    cp /borgmatic-config.yaml /etc/borgmatic/config.yaml
          restartPolicy: Never
          volumes:
          - name: source
            persistentVolumeClaim:
              claimName: "{{ .persistence.source.claim }}"
          - name: borgmatic-config
            configMap:
              name: "borgmatic-config-{{ .name }}"
              items:
                - key: borgmatic-config.yaml
                  path: borgmatic-config.yaml
          {{- if .persistence.secrets.ssh_key }}
          - name: ssh-key
            secret:
              secretName: "{{ .persistence.secrets.ssh_key }}"
              defaultMode: 0400
          {{- end }}
          {{- if .persistence.borgBaseDir }}
            {{- if .persistence.borgBaseDir.claim }}
          - name: borg-base-dir
            persistentVolumeClaim:
              claimName: "{{ .persistence.borgBaseDir.claim }}"
            {{- end }}
          {{- end }}
{{- end }}
