apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-game
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /var/data/ark/ark-game/
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark
    name: ark-game
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-game
  namespace: ark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-game

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-cluster
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /var/data/ark/ark-cluster/
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark
    name: ark-cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-cluster
  namespace: ark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-cluster

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-save-extinction1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /var/data/ark/ark-save-extinction1/
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark
    name: ark-save-extinction1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-save-extinction1
  namespace: ark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-save-extinction1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-save-island1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /var/data/ark/ark-save-island1/
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark
    name: ark-save-island1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-save-island1
  namespace: ark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-save-island1

