apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-game
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  cephfs:
    monitors:
    - 172.16.1.109
    - 172.16.1.107
    - 172.16.1.197
    path: k8s-volumes/ark/ark-game/
    secretRef:
      name: ceph-secret
      namespace: kube-system
    user: admin
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark
    name: ark-game
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-game
  namespace: ark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-game

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-cluster
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  cephfs:
    monitors:
    - 172.16.1.109
    - 172.16.1.107
    - 172.16.1.197
    path: k8s-volumes/ark/ark-cluster/
    secretRef:
      name: ceph-secret
      namespace: kube-system
    user: admin
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark
    name: ark-cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-cluster
  namespace: ark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-cluster

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-save-extinction1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  cephfs:
    monitors:
    - 172.16.1.109
    - 172.16.1.107
    - 172.16.1.197
    path: k8s-volumes/ark/ark-save-extinction1/
    secretRef:
      name: ceph-secret
      namespace: kube-system
    user: admin
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark
    name: ark-save-extinction1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-save-extinction1
  namespace: ark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-save-extinction1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-save-island1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  cephfs:
    monitors:
    - 172.16.1.109
    - 172.16.1.107
    - 172.16.1.197
    path: k8s-volumes/ark/ark-save-island1/
    secretRef:
      name: ceph-secret
      namespace: kube-system
    user: admin
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark
    name: ark-save-island1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-save-island1
  namespace: ark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-save-island1

