# Default values for ark-wes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: LoadBalancer
  loadBalancerIP: 172.16.1.233
  ports:
    - name: island1
      queryudp: 27010
      gameudp: 7770
      gameudp2: 7771
      rcon: 32330

ark-cluster:
  nodeSelector:
    ceph-client: "true"
    kubernetes.io/hostname: "w-dock8"

  image:
    registry: docker.io
    repository: drpsychick/arkserver
    tag: latest-v1.6.61a #bionic
    # repository: wesparish/arkserver
    # tag: latest-v1.6.61a-wes #bionic
    pullSecrets: []
    pullPolicy: Always

  replicaCount: 1

  clusterName: wtopace

  # initContainers:
  #   - name: init-arkmanager-TEST
  #     image: drpsychick/arkserver:latest-v1.6.61a
  #     imagePullPolicy: Always
  #     command:
  #       - /bin/sh
  #       - -c
  #       - |
  #         set -e
  #         arkmanager install --verbose
  #     volumeMounts:
  #       - name: ark-config
  #         mountPath: /ark/config
  #       - name: ark-data
  #         mountPath: /ark/data
  #       - name: ark-save
  #         mountPath: /ark/save
  #       - name: ark-game
  #         mountPath: /ark/game
  #       - name: ark-cluster
  #         mountPath: /ark/cluster
  servers:
    island1:
      # updateOnStart should be enabled only on the first server
      updateOnStart: true
      sessionName: "WTopAce Island"
      message: "Welcome to WTopAce Island"
      map: TheIsland
      password: ""
      maxPlayers: 10
      xpMultiplier: 4
      extraEnvVars:
        - name: am_arkwarnminutes
          value: "30"
      ports:
        queryudp: 27010
        # 2 ports: 7770 and 7771 (created automatically)
        gameudp: 7770
        rcon: 32330
      rcon:
        password: "changeme"
      resources:
        requests:
          cpu: 1
          memory: 4Gi
        limits:
          cpu: 4
          memory: 12Gi
      mods:
        # Dino Tracker
        # https://steamcommunity.com/sharedfiles/filedetails/?id=924933745
        - "924933745"
        # Awesome SpyGlass!
        # https://steamcommunity.com/sharedfiles/filedetails/?id=1404697612
        - "1404697612"
        # Automatic Death Recovery
        # https://steamcommunity.com/sharedfiles/filedetails/?id=1315534671
        - "1315534671"
        # Awesome Teleporters!
        # https://steamcommunity.com/sharedfiles/filedetails/?id=889745138
        - "889745138"
        # Revive my dino
        # https://steamcommunity.com/sharedfiles/filedetails/?id=1957185915
        # https://steamcommunity.com/workshop/filedetails/discussion/1957185915/2666627242543202225/
        - "1957185915"
        # Dino Storage v2
        # https://steamcommunity.com/sharedfiles/filedetails/?id=1609138312
        - "1609138312"
      customConfigMap:
        GameIni: |
          # Extinction Game.ini
          [/script/shootergame.shootergamemode]
          bDisableGenesisMissions=false
          bIgnoreStructuresPreventionVolumes=true
          bGenesisUseStructuresPreventionVolumes=true
          bShowCreativeMode=false
          bAutoUnlockAllEngrams=false
          MaxTribeLogs=1
          bDisableFriendlyFire=true
          bUseCorpseLocator=true
          bDisableStructurePlacementCollision=false
          bAllowUnlimitedRespecs=true
          bPvEDisableFriendlyFire=true
          bFlyerPlatformAllowUnalignedDinoBasing=false
          bDisableLootCrates=false
          bIncreasePvPRespawnInterval=false
          IncreasePvPRespawnIntervalCheckPeriod=300
          IncreasePvPRespawnIntervalMultiplier=2
          IncreasePvPRespawnIntervalBaseAmount=60
          bAutoPvETimer=false
          bAutoPvEUseSystemTime=false
          AutoPvEStartTimeSeconds=0
          AutoPvEStopTimeSeconds=0
          bPvEAllowTribeWar=true
          bPvEAllowTribeWarCancel=false
          MaxAlliancesPerTribe=10
          FastDecayInterval=30
          bAllowCustomRecipes=false
          CustomRecipeEffectivenessMultiplier=1.00000
          CustomRecipeSkillMultiplier=1.00000
          bAllowPlatformSaddleMultiFloors=true
          UseCorpseLifeSpanMultiplier=25.00000
          GlobalPoweredBatteryDurabilityDecreasePerSecond=4
          RandomSupplyCratePoints=false
          # OverrideMaxExperiencePointsPlayer=1
          # OverrideMaxExperiencePointsDino=1
          PlayerHarvestingDamageMultiplier=1.00000
          CraftingSkillBonusMultiplier=1.00000
          DinoHarvestingDamageMultiplier=3.20000
          DinoTurretDamageMultiplier=1.00000
          WildDinoCharacterFoodDrainMultiplier=1.00000
          WildDinoTorporDrainMultiplier=1.00000
          TamedDinoCharacterFoodDrainMultiplier=0.250000
          TamedDinoTorporDrainMultiplier=1.00000
          PassiveTameIntervalMultiplier=1.00000
          ResourceNoReplenishRadiusPlayers=1.00000
          ResourceNoReplenishRadiusStructures=1.00000
          BaseTemperatureMultiplier=0.47500
          GlobalItemDecompositionTimeMultiplier=1.00000
          GlobalCorpseDecompositionTimeMultiplier=1.00000
          CraftXPMultiplier=2.00000
          GenericXPMultiplier=2.00000
          HarvestXPMultiplier=2.00000
          KillXPMultiplier=4.00000
          SpecialXPMultiplier=1.00000
          StructureDamageRepairCooldown=180
          PvPZoneStructureDamageMultiplier=6.00000
          bPassiveDefensesDamageRiderlessDinos=false
          bLimitTurretsInRange=true
          LimitTurretsRange=10000
          LimitTurretsNum=100
          bHardLimitTurretsInRange=true
          PreventOfflinePvPConnectionInvincibleInterval=5.00000
          bDisableDinoRiding=false
          bDisableDinoTaming=false
          bUseTameLimitForStructuresOnly=false
          FastDecayInterval=43200
          GlobalSpoilingTimeMultiplier=1.00000
          BabyImprintingStatScaleMultiplier=1.00000
          BabyImprintAmountMultiplier=1.0
          MatingIntervalMultiplier=1.00000
          LayEggIntervalMultiplier=1.00000
          EggHatchSpeedMultiplier=1.00000
          BabyMatureSpeedMultiplier=1.00000
          BabyCuddleIntervalMultiplier=1.00000
          BabyCuddleGracePeriodMultiplier=1.00000
          BabyCuddleLoseImprintQualitySpeedMultiplier=1.00000
          BabyFoodConsumptionSpeedMultiplier=1.00000
          SupplyCrateLootQualityMultiplier=1.0
          FishingLootQualityMultiplier=1.00000
          CropGrowthSpeedMultiplier=1.00000
          PoopIntervalMultiplier=1.00000
          CropDecaySpeedMultiplier=1.00000
          HairGrowthSpeedMultiplier=1.00000
          KickIdlePlayersPeriod=3600
          PerLevelStatsMultiplier_Player[0]=1
          PerLevelStatsMultiplier_Player[1]=1
          PerLevelStatsMultiplier_Player[2]=1
          PerLevelStatsMultiplier_Player[3]=1
          PerLevelStatsMultiplier_Player[4]=1
          PerLevelStatsMultiplier_Player[5]=1
          PerLevelStatsMultiplier_Player[6]=1
          PerLevelStatsMultiplier_Player[7]=1
          PerLevelStatsMultiplier_Player[8]=1
          PerLevelStatsMultiplier_Player[9]=1
          PerLevelStatsMultiplier_Player[10]=1
          PerLevelStatsMultiplier_Player[11]=1
          PerLevelStatsMultiplier_DinoWild[0]=1
          PerLevelStatsMultiplier_DinoWild[1]=1
          PerLevelStatsMultiplier_DinoWild[2]=1
          PerLevelStatsMultiplier_DinoWild[3]=1
          PerLevelStatsMultiplier_DinoWild[4]=1
          PerLevelStatsMultiplier_DinoWild[5]=1
          PerLevelStatsMultiplier_DinoWild[6]=1
          PerLevelStatsMultiplier_DinoWild[7]=1
          PerLevelStatsMultiplier_DinoWild[8]=1
          PerLevelStatsMultiplier_DinoWild[9]=1
          PerLevelStatsMultiplier_DinoTamed[0]=0.2
          PerLevelStatsMultiplier_DinoTamed[1]=1
          PerLevelStatsMultiplier_DinoTamed[2]=1
          PerLevelStatsMultiplier_DinoTamed[3]=1
          PerLevelStatsMultiplier_DinoTamed[4]=1
          PerLevelStatsMultiplier_DinoTamed[5]=1
          PerLevelStatsMultiplier_DinoTamed[6]=1
          PerLevelStatsMultiplier_DinoTamed[7]=1
          PerLevelStatsMultiplier_DinoTamed[8]=0.17
          PerLevelStatsMultiplier_DinoTamed[9]=1
          PerLevelStatsMultiplier_Tamed_Add[0]=0.14
          PerLevelStatsMultiplier_Tamed_Add[1]=1
          PerLevelStatsMultiplier_Tamed_Add[2]=1
          PerLevelStatsMultiplier_Tamed_Add[3]=1
          PerLevelStatsMultiplier_Tamed_Add[4]=1
          PerLevelStatsMultiplier_Tamed_Add[5]=1
          PerLevelStatsMultiplier_Tamed_Add[6]=1
          PerLevelStatsMultiplier_Tamed_Add[7]=1
          PerLevelStatsMultiplier_Tamed_Add[8]=0.14
          PerLevelStatsMultiplier_Tamed_Add[9]=1
          PerLevelStatsMultiplier_DinoTamed_Affinity[0]=0.44
          PerLevelStatsMultiplier_DinoTamed_Affinity[1]=1
          PerLevelStatsMultiplier_DinoTamed_Affinity[2]=1
          PerLevelStatsMultiplier_DinoTamed_Affinity[3]=1
          PerLevelStatsMultiplier_DinoTamed_Affinity[4]=1
          PerLevelStatsMultiplier_DinoTamed_Affinity[5]=1
          PerLevelStatsMultiplier_DinoTamed_Affinity[6]=1
          PerLevelStatsMultiplier_DinoTamed_Affinity[7]=1
          PerLevelStatsMultiplier_DinoTamed_Affinity[8]=0.44
          PerLevelStatsMultiplier_DinoTamed_Affinity[9]=1
          CnFfhWj=g8UuY.C7Fo
          Z-dnaQveHxyzfSLm=j6JhiFm3Mbp4
        GameUserSettingsIni: |
          [ServerSettings]
          allowThirdPersonPlayer=1
          AllowCaveBuildingPvE=1
          alwaysNotifyPlayerJoined=1
          alwaysNotifyPlayerLeft=1
          bAllowFlyerCarryPvE=1
          bDisableStructureDecayPvE=1
          DayCycleSpeedScale=1.00000
          DayTimeSpeedScale=1.00000
          NightTimeSpeedScale=100.00000
          DinoCharacterFoodDrainMultiplier=1.00000
          DinoCharacterHealthRecoveryMultiplier=1.00000
          DinoCharacterStaminaDrainMultiplier=1.00000
          DinoCountMultiplier=1.00000
          DinoDamageMultiplier=1.00000
          DinoResistanceMultiplier=1.00000
          globalVoiceChat=1
          HarvestAmountMultiplier=1.00000
          HarvestHealthMultiplier=1.00000
          MaxStructuresInRange=6700
          noTributeDownloads=0
          PreventDownloadSurvivors=0
          PreventDownloadItems=0
          PreventDownloadDinos=0
          PlayerCharacterFoodDrainMultiplier=0.250000
          PlayerCharacterHealthRecoveryMultiplier=1.00000
          PlayerCharacterStaminaDrainMultiplier=1.00000
          PlayerCharacterWaterDrainMultiplier=1.00000
          PlayerDamageMultiplier=1.00000
          PlayerResistanceMultiplier=1.00000
          proximityChat=0
          ResourceNoReplenishRadiusPlayers=1.00000
          ResourceNoReplenishRadiusStructures=1.00000
          ResourcesRespawnPeriodMultiplier=1.00000
          ServerAdminPassword=changeme
          ServerCrosshair=0
          serverForceNoHud=0
          serverHardcore=0
          ServerPassword=
          serverPVE=1
          ShowMapPlayerLocation=1
          StructureDamageMultiplier=1.00000
          StructureResistanceMultiplier=1.00000
          TamedDinoDamageMultiplier=1.00000
          TamedDinoResistanceMultiplier=1.00000
          TamingSpeedMultiplier=40.00000
          XPMultiplier=4.00000
          EnablePVPGamma=0
          EnablePVEGamma=0
          SpectatorPassword=
          DifficultyOffset=0.50000
          PvEStructureDecayPeriodMultiplier=1.00000
          PvEStructureDecayDestructionPeriod=1.00000
          Banlist="http://arkdedicated.com/banlist.txt"
          PvPStructureDecay=0
          DisableDinoDecayPvE=0
          PvEDinoDecayPeriodMultiplier=1.00000
          AdminLogging=0
          MaxTamedDinos=8000
          MaxNumbersofPlayersInTribe=20
          BattleNumOfTribestoStartGame=2
          TimeToCollapseROD=100
          BattleAutoStartGameInterval=100
          BattleSuddenDeathInterval=300
          KickIdlePlayersPeriod=1800
          PerPlatformMaxStructuresMultiplier=1.00000
          StructureDamageRepairCooldown=180
          bForceAllStructureLocking=1
          AutoDestroyOldStructuresMultiplier=0.00000
          bUseVSync=0
          MaxPlatformSaddleStructureLimit=100
          bPassiveDefensesDamageRiderlessDinos=1
          RCONPort=32330
          AutoSavePeriodMinutes=20
          RCONServerGameLogBuffer=600
          OverrideStructurePlatformPrevention=0
          PreventOfflinePvPInterval=60.0
          bPvPDinoDecay=1
          bPvPStructureDecay=1
          DisableImprintDinoBuff=1
          AllowAnyoneBabyImprintCuddle=1
          EnableExtraStructurePreventionVolumes=1
          ShowFloatingDamageText=1
          DestroyUnconnectedWaterPipes=0
          OverrideOfficialDifficulty=1.0
          TheMaxStructuresInRange=10500
          MinimumDinoReuploadInterval=0
          PvEAllowStructuresAtSupplyDrops=1
          NPCNetworkStasisRangeScalePlayerCountStart=70
          NPCNetworkStasisRangeScalePlayerCountEnd=120
          NPCNetworkStasisRangeScalePercentEnd=0.50
          MaxPersonalTamedDinos=500
          AutoDestroyDecayedDinos=1
          ClampItemSpoilingTimes=0
          UseOptimizedHarvestingHealth=1
          AllowCrateSpawnsOnTopOfStructures=1
          ForceFlyerExplosives=0
          PreventOfflinePvP=1
          AllowFlyingStaminaRecovery=1
          AllowMultipleAttachedC4=1
          OxygenSwimSpeedStatMultiplier=1.00
          bPvEDisableFriendlyFire=1
          ServerAutoForceRespawnWildDinosInterval=86400
          DisableWeatherFog=1
          RandomSupplyCratePoints=0
          CrossARKAllowForeignDinoDownloads=0
          PersonalTamedDinosSaddleStructureCost=19
          # [/script/engine.gamesession]
          # MaxPlayers=10
          # [SessionSettings]
          # SessionName=WTopAce Island
          # [MessageOfTheDay]
          # Duration=30
          # Message=WTopAce Island
        # Doesn't work because the configmap creates /ark/config as root and
        # the entrypoint.sh script can't write to it
        # crontab: |
        #   # Wes overrides
        #   # Example of job definition:
        #   # .---------------- minute (0 - 59)
        #   # |  .------------- hour (0 - 23)
        #   # |  |  .---------- day of month (1 - 31)
        #   # |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
        #   # |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
        #   # |  |  |  |  |
        #   # *  *  *  *  * user-name  command to be executed

        #   */30 * * * * arkmanager update --update-mods --warn --saveworld
        #   10 */8 * * * arkmanager saveworld && arkmanager backup
        #   # Disabling the restart, don't see the point and causes issues
        #   # with livenessProbes
        #   #15 10 * * * arkmanager restart --warn --saveworld


  persistence:
    enabled: true

    # game files from steam, the largest volume, includes installed mods
    game:
      existingClaim: ark-game
    cluster:
      existingClaim: ark-cluster
    save:
      existingClaim: ark-save

  startupProbe:
    # With 10s interval, gives us 1h to startup
    failureThreshold: 348
    initialDelaySeconds: 10
  livenessProbe:
    # With 10s interval, gives us 15m before failing
    failureThreshold: 90