apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-dns-proxy.fullname" . }}
  labels:
    {{- include "cloudflare-dns-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.dns }}
      targetPort: 5053
      protocol: UDP
      name: dns
    - port: {{ .Values.service.port.metrics }}
      targetPort: 39055
      protocol: TCP
      name: metrics
  externalTrafficPolicy: Local
  selector:
    {{- include "cloudflare-dns-proxy.selectorLabels" . | nindent 4 }}
