apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-dns-proxy.fullname" . }}-vip
  labels:
    {{- include "cloudflare-dns-proxy.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
    - port: {{ .Values.service.port.dns }}
      targetPort: 5053
      protocol: UDP
      name: dns
  selector:
    {{- include "cloudflare-dns-proxy.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  # Forced sourceIP to be kept
  externalTrafficPolicy: Local
  loadBalancerIP: 172.16.1.230
