nginx-ingress-wes:
  ingress-nginx:
    controller:
      ingressClass: nginx-wes
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.4.10
        annotations:
          metallb.universe.tf/address-pool: default
      kind: DaemonSet
      nodeSelector:
        ingress: "true"