version: '2'
services:
  claymore-amd:
    init: true
    image: wesparish/ethminer:amd-v0.13.0
    devices:
    - /dev/dri:/dev/dri:rwm
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    environment:
      WALLET_ADDRESS: ${WALLET_ADDRESS}
      HOSTS: ${HOSTS}
    labels:
      io.rancher.scheduler.affinity:host_label: gpu-type=amd,miner=claymore
      io.rancher.scheduler.affinity:container_label_ne: miner=true
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    privileged: true
