apiVersion: v1
kind: Service
metadata:
  name: {{ include "eqbcs.fullname" . }}
  labels:
    {{- include "eqbcs.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: default
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2112
      protocol: TCP
      name: eqbcs
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    {{- include "eqbcs.selectorLabels" . | nindent 4 }}
  externalTrafficPolicy: Local
  loadBalancerIP: 172.16.1.232
