immich:
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          # Keys:
          #  adminPasswordKey: postgres-password
          #  userPasswordKey: password
          #  replicationPasswordKey: replication-password
          existingSecret: postgres-secret
    primary:
      persistence:
        existingClaim: immich-data
        subPath: postgres-data

  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        existingClaim: immich-data
        subPath: redis-data

  common_env:
    JWT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: postgres-password
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: postgres-password

  server:
    image:
      tag:  v1.36.2_56-dev

  microservice:
    image:
      tag: v1.36.2_56-dev

  machine_learning:
    image:
      tag: v1.36.2_56-dev

  web:
    image:
      tag: v1.36.2_56-dev

  proxy:
    image:
      tag: v1.36.2_56-dev

  ingress:
    main:
      enabled: true
      primary: false
      annotations:
        kubernetes.io/ingress.class: "nginx-wes"
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 2000m
      hosts:
        - host: immich.elastiscale.net
          paths:
            - path: "/"
      tls:
        - secretName: immich-elastiscale.net
          hosts:
            - immich.elastiscale.net

  persistence:
    library:
      enabled: true
      type: pvc
      existingClaim: immich-data
      subPath: immich
