immich:
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          # Keys:
          #  adminPasswordKey: postgres-password
          #  userPasswordKey: password
          #  replicationPasswordKey: replication-password
          existingSecret: postgres-secret
    primary:
      persistence:
        existingClaim: immich-data
        subPath: postgres-data

  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        existingClaim: immich-data
        subPath: redis-data


  immich:
    persistence:
      library:
        enabled: true
        type: pvc
        existingClaim: immich-data
        # Seems to be broken? 20230608
        subPath: immich

  typesense:
    enabled: true
    persistence:
      tsdata:
        enabled: true
        existingClaim: immich-typesense-data
      library:
        enabled: true
        type: pvc
        existingClaim: immich-data
        subPath: immich
    image:
      repository: docker.io/typesense/typesense
      pullPolicy: IfNotPresent

  env:
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: postgres-password

  server:
    image:
      pullPolicy: Always
    persistence:
      library:
        subPath: immich

    ingress:
      main:
        enabled: true
        # primary: false
        annotations:
          kubernetes.io/ingress.class: "nginx-wes"
          kubernetes.io/tls-acme: "true"
          # proxy-body-size is set to 0 to remove the body limit on file uploads
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: immich.elastiscale.net
            paths:
              - path: "/"
        tls:
          - secretName: immich-elastiscale.net
            hosts:
              - immich.elastiscale.net

  microservices:
    image:
      pullPolicy: Always
    persistence:
      library:
        subPath: immich

  machine-learning:
    image:
      pullPolicy: Always
    persistence:
      library:
        subPath: immich

  web:
    image:
      pullPolicy: Always
    persistence:
      library:
        subPath: immich
