apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shinobi.fullname" . }}
  labels:
    app: {{ template "shinobi.name" . }}
    chart: {{ template "shinobi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "shinobi.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "shinobi.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: shinobi-config
          persistentVolumeClaim:
            claimName: shinobi-config
        - name: shinobi-datadir
          persistentVolumeClaim:
            claimName: shinobi-datadir
        - name: shinobi-videos
          persistentVolumeClaim:
            claimName: shinobi-videos
        - name: etc-localtime
          hostPath:
            path: /etc/localtime
            type: ""
        - name: etc-timezone
          hostPath:
            path: /etc/timezone
            type: File
        - name: shinobi-shm-temp
          hostPath:
            path: /dev/shm/shinobiDockerTmp
            type: ""
      containers:
        - name: {{ .Chart.Name }}-mariadb
          image: "{{ .Values.image.mariadb.repository }}:{{ .Values.image.mariadb.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_USER
              value: "majesticflame"
            - name: MYSQL_PASSWORD
              value: "password"
          volumeMounts:
            - name: shinobi-datadir
              mountPath: /var/lib/mysql
          ports:
            - name: mariadb
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources.owncloud | nindent 12 }}
        - name: {{ .Chart.Name }}-shinobi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ADMIN_USER
            value: "wes@elastiscale.net"
          - name: ADMIN_PASSWORD
            value: "{{ .Values.shinobi.admin.password }}"
          - name: CRON_KEY
            value: "{{ .Values.shinobi.cronKey }}"
          - name: PLUGINKEY_MOTION
            value: "a0746424-2a05-491f-b2ae-b697605cf538"
          - name: PLUGINKEY_OPENALPR
            value: "c2b0075d-bf2c-40f6-9032-c0e2d099909a"
          - name: MOTION_HOST
            value: "localhost"
          - name: MOTION_PORT
            value: "8080"
          - name: MYSQL_HOST
            value: "127.0.0.1"
          - name: MYSQL_DATABASE
            value: "ccio"
          - name: MYSQL_ROOT_USER
            value: "majesticflame"
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_USER
            value: "majesticflame"
          - name: MYSQL_PASSWORD
            value: "password"

          volumeMounts:
            - name: shinobi-config
              mountPath: /config
            - name: shinobi-videos
              mountPath: /opt/shinobi/videos
            - name: etc-localtime 
              mountPath: /etc/localtime
            - name: etc-timezone
              mountPath: /etc/timezone
            - name: shinobi-shm-temp
              mountPath: /dev/shm/streams
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
