apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "shinobi.fullname" . }}
  labels:
    app: {{ template "shinobi.name" . }}
    chart: {{ template "shinobi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "shinobi.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "shinobi.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: shinobi-config
          persistentVolumeClaim:
            claimName: shinobi-config
        - name: shinobi-datadir
          persistentVolumeClaim:
            claimName: shinobi-datadir
        - name: shinobi-videos
          persistentVolumeClaim:
            claimName: shinobi-videos
        - name: etc-localtime
          hostPath:
            path: /etc/localtime
            type: ""
        - name: etc-timezone
          hostPath:
            path: /etc/timezone
            type: File
        - name: shinobi-shm-temp
          hostPath:
            path: /dev/shm/shinobiDockerTmp
            type: ""
        - name: disable-super-json
          configMap:
            name: shinobi-config
      containers:
        - name: {{ .Chart.Name }}-shinobi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ADMIN_USER
            value: "wes@elastiscale.net"
          - name: ADMIN_PASSWORD
            value: "{{ .Values.shinobi.admin.password }}"
#          - name: MYSQL_USER
#            value: "shinobi"
#          - name: MYSQL_PASSWORD
#            value: "{{ .Values.mariadb.db.password }}"
#          - name: MYSQL_HOST
#            value: "{{ .Release.Name }}-mariadb"
#          - name: MYSQL_DATABASE
#            value: "shinobi"
#          - name: MYSQL_ROOT_PASSWORD
#            value: "{{ .Values.mariadb.rootUser.password }}"
#          - name: MYSQL_ROOT_USER
#            value: "root"
          - name: CRON_KEY
            value: "{{ .Values.shinobi.cronKey }}"
          - name: PLUGINKEY_MOTION
            value: "a0746424-2a05-491f-b2ae-b697605cf538"
          - name: PLUGINKEY_OPENALPR
            value: "c2b0075d-bf2c-40f6-9032-c0e2d099909a"
          - name: MOTION_HOST
            value: "localhost"
          - name: MOTION_PORT
            value: "8080"
          volumeMounts:
            - name: shinobi-config
              mountPath: /config
            - name: shinobi-datadir
              mountPath: /var/lib/mysql
            - name: shinobi-videos
              mountPath: /opt/shinobi/videos
            - name: etc-localtime 
              mountPath: /etc/localtime
            - name: etc-timezone
              mountPath: /etc/timezone
            - name: shinobi-shm-temp
              mountPath: /dev/shm/streams
            - name: disable-super-json
              mountPath: /opt/shinobi/super.json
              subPath: super.json
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
