{{- if .Values.deluge.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "plex-wes.fullname" . }}-deluge
  {{- with .Values.deluge.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.deluge.ingress.fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "plex-wes.fullname" . }}-deluge
                port: 
                  number: {{ .Values.deluge.service.port }}
  tls:
    - hosts:
      - {{ .Values.deluge.ingress.fqdn }}
      secretName: {{ .Values.deluge.ingress.secretName }}
{{- end }}
