# Default values for nginx-ingress-wes-metallb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx-ingress:
  controller:
    ingressClass: nginx-wes-metallb
    service:
      type: LoadBalancer
      loadBalancerIp: 172.16.1.221
    kind: DaemonSet
    nodeSelector:
      ingress: "true"
