apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "claymore-nvidia-scalable.fullname" . }}
  labels:
    app: {{ template "claymore-nvidia-scalable.name" . }}
    chart: {{ template "claymore-nvidia-scalable.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "claymore-nvidia-scalable.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "claymore-nvidia-scalable.name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In
                values:
                - nvidia
              - key: miner
                operator: In
                values:
                - {{ .Values.claymore.scalablelabel }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: container.type
                operator: In
                values:
                - miner
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          - env:
            - name: WALLET_ADDRESS
              value: {{ .Values.claymore.wallet }}
            - name: CLAYMORE_OPTS
              value: {{ .Values.claymore.options }}
            - name: HOSTS
              value: {{ .Values.claymore.poolhosts }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            initialDelaySeconds: 30
            exec:
              command:
                - "pgrep"
                - "ethdcrminer64"
          readinessProbe:
            initialDelaySeconds: 30
            exec:
              command:
                - "pgrep"
                - "ethdcrminer64"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
