apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jibri.fullname" . }}-other
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
data:
  finalize.sh: |
    {{- if .Values.jibri.custom.other._finalize_sh }}
      {{- .Values.jibri.custom.other._finalize_sh | nindent 4 }}
    {{- else }}
    # Not using a custom finalize.sh
    {{ end }}
