apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "virt-manager-wes.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "virt-manager-wes.name" . }}
    helm.sh/chart: {{ include "virt-manager-wes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "virt-manager-wes.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "virt-manager-wes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5800
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: virt-manager-data
            mountPath: /config
          - name: dev-urandom
            mountPath: /dev/urandom
          - name: ssh-config
            mountPath: /etc/ssh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: virt-manager-data
        persistentVolumeClaim:
          claimName: {{ .Values.virtManager.persistence.existingClaim }}
      - name: dev-urandom
        hostPath:
          path: /dev/urandom
      - name: ssh-config
        configMap:
          name: ssh-config
          items:
          - key: ssh_config
            path: ssh_config
