apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  cephfs:
    monitors:
    - 172.16.1.109
    - 172.16.1.107
    - 172.16.1.197
    path: k8s-volumes/authentik-data/
    secretRef:
      name: ceph-secret
      namespace: kube-system
    user: admin
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: authentik
    name: authentik-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data
  namespace: authentik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: authentik-data