apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-wes.fullname" . }}-udp
  labels:
    {{- include "ark-wes.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing-key"
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  publishNotReadyAddresses: true
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .queryudp }}
      targetPort: {{ .queryudp }}
      protocol: UDP
      name: queryudp-{{ .name }}
    - port: {{ .gameudp }}
      targetPort: {{ .gameudp }}
      protocol: UDP
      name: gameudp-{{ .name }}
    - port: {{ .gameudp2 }}
      targetPort: {{ .gameudp2 }}
      protocol: UDP
      name: gameudp2-{{ .name }}
  selector:
    app.kubernetes.io/component: {{ .name }}
    app.kubernetes.io/instance: ark
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-wes.fullname" . }}-tcp
  labels:
    {{- include "ark-wes.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing-key"
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  publishNotReadyAddresses: true
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .rcon }}
      targetPort: {{ .rcon }}
      protocol: TCP
      name: rcon-{{ .name }}
  selector:
    app.kubernetes.io/component: {{ .name }}
    app.kubernetes.io/instance: ark
  {{- end }}