apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rocketchat-wes.fullname" . }}-pushgateway
  labels:
    app.kubernetes.io/name: {{ include "rocketchat-wes.name" . }}-pushgateway
    helm.sh/chart: {{ include "rocketchat-wes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rocketchat-wes.name" . }}-pushgateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rocketchat-wes.name" . }}-pushgateway
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-pushgateway
          image: "{{ .Values.image.pushgateway.repository }}:{{ .Values.image.pushgateway.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: 5000
            failureThreshold: 36
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status
              port: 5000
            failureThreshold: 36
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
