apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rocketchat-backup
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: rocketchat-backup
            image: mongo
            volumeMounts:
            - name: rocketchat-backup
              mountPath: /rocketchat-backup/
            command: ["/bin/bash"]
            args:
            - -c
            - echo Backing up rocketchat mongodb to /rocketchat-backup/$(date +\%Y\%m\%d-\%H\%M\%S) && mongodump -o /rocketchat-backup/$(date +\%Y\%m\%d-\%H\%M\%S) --gzip --host rocketchat-mongodb.rocketchat.svc.cluster.local && find /rocketchat-backup/ -mtime +30 -delete
          restartPolicy: OnFailure
          volumes:
          - name: rocketchat-backup
            persistentVolumeClaim:
              claimName: rocketchat-backup
