apiVersion: v1
kind: Service
metadata:
  name: rocketchat-loadbalancer-svc
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rocketchat
  type: LoadBalancer
  loadBalancerIP: 172.16.1.221
