apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns-service
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 172.16.1.222
