apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ark-ascended-wes.fullname" . }}-game-ini
  labels:
    {{- include "ark-ascended-wes.labels" . | nindent 4 }}
data:
  Game.ini: |
{{ .Values.gameIni | indent 4 }}
  GameUserSettings.ini: |
{{ .Values.gameUserSettingsIni | indent 4 }}
