apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /data/k8s-volumes/frigate-data/
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: frigate
    name: frigate-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data
  namespace: frigate
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: frigate-data
