apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: rocketchat-wes
version: 0.1.0

dependencies:
  - name: mongodb
    # version: "12.1.31"
    version: "13.18.5"
    repository: "https://charts.bitnami.com/bitnami"
