---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-server-config
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: ceph-csi
    volumeAttributes:
      # optional file system to be mounted
      "fsName": "test1"
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "6c2190ab-5525-4345-8dba-8c3151c4e530"
      "staticVolume": "true"
      "rootPath": /k8s-volumes/satisfactory-server-config/
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: satisfactory-server-config
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-server-config
  namespace: satisfactory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: satisfactory-server-config
