version: '2'
services:
  claymore-nvidia:
    start_on_create: false
  claymore-nvidia-scalable:
    start_on_create: true
catalog:
  name: Claymore Nvidia
  version: 10.0-1.2
  description: Claymore Nvidia
  questions:
    - variable: WALLET_ADDRESS
      label: Wallet address
      default: 0x559db2865e1f099d63037c3ae4a6c8cc1106c819
      type: string
    - variable: HOSTS
      label: Pool Hosts e.g. eth-us-east1.nanopool.org:9999:x:0:0 eth-us-west1.nanopool.org:9999:x:0:0
      default: eth-us-east1.nanopool.org:9999:x:0:0 eth-us-west1.nanopool.org:9999:x:0:0
      type: string
    - variable: CLAYMORE_OPTS
      label: Extra Claymore Options
      default: -r 1 -nofee 1 -mode 1
      type: string
    - variable: CLAYMORE_SCALABLE_LABEL
      label: Scheduling label for claymore_amd_scalable service
      default: claymore-scalable
      type: string
    - variable: CLAYMORE_LABEL
      label: Scheduling label for claymore_amd service
      default: claymore
      type: string
