apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required - {{ .Values.name }}
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/proxy-body-size: 200m
spec:
  rules:
    - host: {{ .Values.name }}.elastiscale.net
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .service.port }}
  tls:
    - hosts:
      - {{ .Values.name }}.elastiscale.net
      secretName: {{ .Values.name }}-elastiscale.net
