apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name | lower | quote }}
  annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      {{- if .Values.auth }}
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required - {{ .Values.name }}
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      {{- end }}
      {{- if .Values.backendProtocol }}
      nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.backendProtocol }}
      {{- end }}
      nginx.ingress.kubernetes.io/proxy-body-size: 200m
spec:
  rules:
    - host: {{ .Values.name | lower }}.elastiscale.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                  name: {{ .Values.name | lower }}
                  port:
                      number: {{ .Values.endpoint.targetPort }}
  tls:
    - hosts:
      - {{ .Values.name | lower }}.elastiscale.net
      secretName: {{ .Values.name | lower }}-elastiscale.net
