---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-ascended-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 80Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: ceph-csi
    volumeAttributes:
      # optional file system to be mounted
      "fsName": "test1"
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "6c2190ab-5525-4345-8dba-8c3151c4e530"
      "staticVolume": "true"
      # Must already exist on cephfs -- a staticVolume mount will not create it. See
      # charts/ark-ascended-wes/README.md.
      "rootPath": /k8s-volumes/ark-ascended/data/
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: ark-ascended-data
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ark-ascended
    name: ark-ascended-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-ascended-data
  namespace: ark-ascended
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ark-ascended-data
