---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wchat-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: ceph-csi
    volumeAttributes:
      "fsName": "test1"
      "clusterID": "6c2190ab-5525-4345-8dba-8c3151c4e530"
      "staticVolume": "true"
      "rootPath": /k8s-volumes/wchat/
    volumeHandle: wchat-data
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wchat-data
  namespace: wchat
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: wchat-data
