apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "elastalert.fullname" . }}
  labels:
    app: {{ template "elastalert.name" . }}
    chart: {{ template "elastalert.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "elastalert.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "elastalert.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.elastalert.elastalertConfigPVC }}
        - name: rules
          persistentVolumeClaim:
            claimName: {{ .Values.elastalert.elastalertRulesPVC }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Values.elastalert.elastalertLogsPVC }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONTAINER_TIMEZONE
              value: America/Chicago
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.elastalert.elasticsearchHost }}
            - name: ELASTICSEARCH_PORT
              value: '{{ .Values.elastalert.elasticsearchPort }}'
            - name: SET_CONTAINER_TIMEZONE
              value: 'True'
          livenessProbe:
            exec:
              command: ["pgrep", "-f", "elastalert.elastalert"]
          readinessProbe:
            exec:
              command: ["pgrep", "-f", "elastalert.elastalert"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
