apiVersion: v1
name: gpu-monitor-amd
version: 1.0.0
appVersion: 1.2.0
description: Reports GPU information to elasticsearch
keywords:
- logging
sources:
- https://github.com/wesparish/docker-gpu-monitor
maintainers:
- name: wes
  email: wes@elastiscale.net

