{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homer-k8s.serviceAccountName" . }}
  labels:
    {{- include "homer-k8s.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homer-k8s.serviceAccountName" . }}
rules:
- apiGroups: ["", "networking.k8s.io", "discovery.k8s.io"]
  resources: ["ingresses", "endpoints"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homer-k8s.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "homer-k8s.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "homer-k8s.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
