version: '2'
services:
  plexserver:
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 32400
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  plexpy:
    start_on_create: true
  deluge:
    start_on_create: true
catalog:
  name: Plex
  version: 1
  description: Plex
