apiVersion: v1
kind: Service
metadata:
  name: es-loadbalancer-service
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: http-lb
    protocol: TCP
    port: {{ .Values.elasticsearch.httpPort }}
  - name: transport-lb
    protocol: TCP
    port: {{ .Values.elasticsearch.transportPort }}
  selector:
    app: elasticsearch-ssd-master
    chart: elasticsearch-7.2.0
    heritage: Tiller
    release: elasticsearch-ssd
  type: LoadBalancer
  loadBalancerIP: 10.2.2.231
