node-red:
  persistence:
    enabled: true
    existingClaim: node-red-data

  ingress:
    enabled: true
    className: "nginx-wes"
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 2000m
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy-authentik.elastiscale.net/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy-authentik.elastiscale.net/oauth2/auth
    hosts:
      - host: node-red.elastiscale.net
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - secretName: node-red-elastiscale.net
        hosts:
          - node-red.elastiscale.net
        certificate:
          enabled: false
  nodeSelector:
    ceph-client: "true"

  settings:
    name: settings-config
    configMapName: settings-config

  env:
    - name: TZ
      value: "America/Chicago"
    - name: GIT_SSH_COMMAND
      value: "ssh -i /data/projects/.sshkeys/__default_node-red"

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000

  securityContext:
    runAsGroup: 1000
    runAsUser: 1000

