# Default values for the-spaghetti-detective.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  web:
    repository: thespaghettidetective/web
    tag: 0.95
    pullPolicy: Always
  ml_api:
    repository: thespaghettidetective/ml_ap
    tag: 0.95
    pullPolicy: Always
  redis:
    repository: redis
    tag: "5.0"
    pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3334

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-wes
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
  paths:
    - /
  hosts:
    - tsd.elastiscale.net
  tls:
    - secretName: tsd-elastiscale.net
      hosts:
        - tsd.elastiscale.net

resources: 
  web: {}
  ml_api: {}
  redis: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  ceph-client: "true"

tolerations: []

affinity: {}
