apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ollama-wes.fullname" . }}-llamacoder
  labels:
    {{- include "ollama-wes.labels" . | nindent 4 }}
    appName: llamacoder
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ollama-wes.selectorLabels" . | nindent 6 }}
      appName: llamacoder
  template:
    metadata:
      {{- with .Values.ollamachild.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ollama-wes.selectorLabels" . | nindent 8 }}
        appName: llamacoder
    spec:
      {{- with .Values.ollamachild.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ollama-wes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ollamachild.image.repository }}:{{ .Values.ollamachild.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ollamachild.pullPolicy }}
          env:
          {{- if .Values.ollamachild.gpu.enabled }}
            - name: PATH
              value: /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: LD_LIBRARY_PATH
              value: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
          {{- end }}
          {{- with .Values.ollamachild.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      {{- with .Values.ollamachild.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ollamachild.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ollamachild.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
