apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama-wes.fullname" . }}-llamacoder
  labels:
    {{- include "ollama-wes.labels" . | nindent 4 }}
    appName: llamacoder
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: ollama
    app.kubernetes.io/instance: ollama-wes
    appName: llamacoder