{{- if .Values.ingressGotify.enabled -}}
{{- $fullName := include "rocketchat-wes.fullname" . -}}
{{- $svcPort := "80" -}}
{{- if and .Values.ingressGotify.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingressGotify.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingressGotify.annotations "kubernetes.io/ingress.class" .Values.ingressGotify.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-gotify
  labels:
    {{- include "rocketchat-wes.labels" . | nindent 4 }}
    component: gotify
  {{- with .Values.ingressGotify.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingressGotify.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingressGotify.className }}
  {{- end }}
  {{- if .Values.ingressGotify.tls }}
  tls:
    {{- range .Values.ingressGotify.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingressGotify.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-gotify
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-gotify
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
