# Default values for plex-wes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  plex:
    repository: plexinc/pms-docker
    tag: plexpass
  deluge:
    repository: wesparish/deluge
    tag: latest
  plexpy:
    repository: tautulli/tautulli
    tag: latest
  radarr:
    repository: hotio/radarr
    tag: release
  sonarr:
    repository: hotio/sonarr
    tag: release
  readarr:
    repository: ghcr.io/hotio/readarr
    tag: latest
  prowlarr:
    repository: hotio/prowlarr
    tag: testing
  lidarr:
    repository: hotio/lidarr
    tag: release
  overseerr:
    repository: hotio/overseerr
    tag: release
  qbittorrent:
    repository: hotio/qbittorrent
    tag: release
  ersatztv:
    repository: jasongdove/ersatztv
    tag: v0.6.8
  zap2xml:
    repository: shuaiscott/zap2xml
    tag: latest
  jellyfin:
    repository: ghcr.io/hotio/jellyfin
    tag: latest
  watchstate:
    repository: ghcr.io/arabcoders/watchstate
    tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

auth: wes:$apr1$sLLQK9lR$NBDb6NtuzOC6sTHxZ1tuC0

plex:
  # Unused if blank
  claimToken:
  hostname: plexserver-kube
  advertiseIPs: https://plex.elastiscale.net:443,http://plex.elastiscale.net:80
  allowedNetworks: 172.16.0.0/16
  uid: 1000
  gid: 1000
  persistence:
    plexConfig: plex-config
    plexData: plex-data
    delugeConfig: deluge-config
    plexpyData: plexpy-data
    servarrData: servarr-data
  service:
    annotations:
      metallb.universe.tf/address-pool: default
    type: ClusterIP
    port: 32400
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    fqdn: plex.elastiscale.net
    secretName: plex-elastiscale.net

deluge:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
    fqdn: bt.elastiscale.net
    secretName: bt-elastiscale.net
  service:
    type: ClusterIP
    port: 8282

allServarr:
  puid: 1000
  pgid: 1000
  tz: America/Chicago

radarr:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
    fqdn: radarr.elastiscale.net
    secretName: radarr-elastiscale.net
  service:
    type: ClusterIP
    port: 7878

sonarr:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
    fqdn: sonarr.elastiscale.net
    secretName: sonarr-elastiscale.net
  service:
    type: ClusterIP
    port: 8989

readarr:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
    fqdn: readarr.elastiscale.net
    secretName: readarr-elastiscale.net
  service:
    type: ClusterIP
    port: 8787

jellyfin:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      # nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
      # nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
    fqdn: jellyfin.elastiscale.net
    secretName: jellyfin-elastiscale.net
  service:
    type: ClusterIP
    port: 8096

watchstate:
  # ingress:
  #   enabled: true
  #   annotations:
  #     kubernetes.io/ingress.class: "nginx-wes"
  #     kubernetes.io/tls-acme: "true"
  #     nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
  #     nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
  #   fqdn: readarr.elastiscale.net
  #   secretName: readarr-elastiscale.net
  service:
    type: ClusterIP
    port: 8080

prowlarr:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
    fqdn: prowlarr.elastiscale.net
    secretName: prowlarr-elastiscale.net
  service:
    type: ClusterIP
    port: 9696

lidarr:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
    fqdn: lidarr.elastiscale.net
    secretName: lidarr-elastiscale.net
  service:
    type: ClusterIP
    port: 8686

overseerr:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
#      nginx.ingress.kubernetes.io/auth-realm: Authentication Required - Overseerr
#      nginx.ingress.kubernetes.io/auth-secret: basic-auth
#      nginx.ingress.kubernetes.io/auth-type: basic
    fqdn: overseerr.elastiscale.net
    secretName: overseerr-elastiscale.net
  service:
    type: ClusterIP
    port: 5055

qbittorrent:
  vpn:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
    fqdn: qbt.elastiscale.net
    secretName: qbt-elastiscale.net
  service:
    type: ClusterIP
    port: 8080

plexpy:
  timezone: America/Chicago
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
    fqdn: plexpy.elastiscale.net
    secretName: plexpy-elastiscale.net
  service:
    type: ClusterIP
    port: 8181

ersatztv:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.elastiscale.net/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.elastiscale.net/oauth2/auth
    fqdn: ersatztv.elastiscale.net
    secretName: ersatztv-elastiscale.net
  service:
    type: ClusterIP
    port: 8409
    nodePort: 32222

zap2xml:
  xmltvFilename: "xmltv.xml"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
