apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: process-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: process-exporter
  endpoints:
  - port: http

