---
version: "3"

vars:
  MKDOCS_CONFIG_FILE: .ci/mkdocs/mkdocs.yaml

tasks:
  build:
    desc: >
      Build documentation using mkdocs
    cmds:
      - mkdocs build --config-file ./.ci/mkdocs/mkdocs.yaml
    silent: true

  serve:
    desc: >
      Start development server on http://localhost:{{ .PORT }} using mkdocs
    vars:
      PORT: 8000
    cmds:
      - mkdocs serve --config-file ./.ci/mkdocs/mkdocs.yaml --dev-addr localhost:{{ .PORT }} --livereload
    silent: true
