---
version: "3"

tasks:
  init:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install --install-hooks --config .ci/pre-commit/config.yaml

  update:
    desc: Update pre-commit hooks
    cmds:
      - pre-commit autoupdate --config .ci/pre-commit/config.yaml

  run:
    desc: Run pre-commit
    cmds:
      - pre-commit run --config .ci/pre-commit/config.yaml

  run-all:
    desc: Run pre-commit on all files
    cmds:
      - pre-commit run --all-files --config .ci/pre-commit/config.yaml
