apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
#    field.cattle.io/creatorId: user-d84z4
  creationTimestamp: 2018-06-30T12:21:23Z
  generation: 21
  labels:
    app: claymore-amd-scalable
#    workload.user.cattle.io/workloadselector: deployment-claymore-amd-claymore-amd-scalable
  name: claymore-amd-scalable
  #namespace: claymore-amd
  resourceVersion: "1705126"
  selfLink: /apis/apps/v1beta2/namespaces/claymore-amd/deployments/claymore-amd-scalable
  uid: 1a8326e7-7c60-11e8-9a86-c4346b932458
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: claymore-amd-scalable
#      workload.user.cattle.io/workloadselector: deployment-claymore-amd-claymore-amd-scalable
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
#      annotations:
#        field.cattle.io/ports: '[[{"containerPort":30333,"dnsName":"claymore-amd-scalable-nodeport","kind":"NodePort","name":"3333tcp33331","protocol":"TCP","sourcePort":3333}]]'
      creationTimestamp: null
      labels:
#        workload.user.cattle.io/workloadselector: deployment-claymore-amd-claymore-amd-scalable
        container.type: miner
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In
                values:
                - amd
              - key: miner
                operator: In
                values:
                - {{ .Values.claymore.scalablelabel }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: container.type
                operator: In
                values:
                - miner
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: WALLET_ADDRESS
          value: {{ .Values.claymore.wallet }}
        - name: CLAYMORE_OPTS
          value: {{ .Values.claymore.options }}
        - name: HOSTS
          value: {{ .Values.claymore.poolhosts }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: wesparish/claymore:amd-v11.5-4
        imagePullPolicy: Always
        name: claymore-amd-scalable
        ports:
        - containerPort: 30333
          name: 3333tcp33331
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - ALL
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /dev/dri
          name: dev-dri
        - mountPath: /sys
          name: sys
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev/dri
          type: ""
        name: dev-dri
      - hostPath:
          path: /sys
          type: ""
        name: sys
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-06-30T12:45:54Z
    lastUpdateTime: 2018-06-30T12:45:54Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-06-30T20:11:49Z
    lastUpdateTime: 2018-07-08T13:05:51Z
    message: ReplicaSet "claymore-amd-scalable-6cf85ff8cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 21
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
