apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "claymore-amd-scalable.fullname" . }}
  labels:
    app: {{ template "claymore-amd-scalable.name" . }}
    chart: {{ template "claymore-amd-scalable.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "claymore-amd-scalable.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "claymore-amd-scalable.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: WALLET_ADDRESS
              value: {{ .Values.claymore.wallet }}
            - name: CLAYMORE_OPTS
              value: {{ .Values.claymore.options }}
            - name: HOSTS
              value: {{ .Values.claymore.poolhosts }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /sys
            name: sys
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
              - ALL
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          livenessProbe:
            initialDelaySeconds: 30
            exec:
              command:
                - "pgrep"
                - "ethdcrminer64"
          readinessProbe:
            initialDelaySeconds: 30
            exec:
              command:
                - "pgrep"
                - "ethdcrminer64"
          resources:
            requests:
              amd.com/gpu: {{ .Values.claymore.gpusperpod }}
            limits:
              amd.com/gpu: {{ .Values.claymore.gpusperpod }}
      volumes:
        - hostPath:
            path: /sys
            type: ""
          name: sys
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      nodeSelector:
        miner: {{ .Values.claymore.scalablelabel }}
    {{- with .Values.nodeSelector }}
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
