apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freepbx-wes.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    helm.sh/chart: {{ include "freepbx-wes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
#        - name: {{ .Chart.Name }}-mariadb
#          image: "{{ .Values.image.mariadb.repository }}:{{ .Values.image.mariadb.tag }}"
#          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          env:
#            - name: MYSQL_ALLOW_EMPTY_PASSWORD
#              value: "true"
#            - name: MYSQL_ROOT_PASSWORD
#              value: "password"
#            - name: MYSQL_USER
#              value: "majesticflame"
#            - name: MYSQL_PASSWORD
#              value: "password"
#            - name: MYSQL_DATABASE
#              value: "asterisk"
#          volumeMounts:
#            - name: asterisk-data
#              mountPath: /var/lib/mysql
#              subPath: mysql
#          ports:
#            - name: mariadb
#              containerPort: 3306
#              protocol: TCP
#          livenessProbe:
#            tcpSocket:
#              port: 3306
#            initialDelaySeconds: 120
#            timeoutSeconds: 5
#            failureThreshold: 6
#          readinessProbe:
#            tcpSocket:
#              port: 3306
#            initialDelaySeconds: 30
#            timeoutSeconds: 3
#            periodSeconds: 5
#          resources:
#            {{- toYaml .Values.resources | nindent 12 }}

        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
#            - name: "DB_EMBEDDED"
#              value: "FALSE"
#            - name: DB_HOST
#              value: "127.0.0.1"
#            - name: DB_PORT
#              value: "3306"
#            - name: DB_NAME
#              value: asterisk
#            - name: DB_USER
#              value: majesticflame
#            - name: DB_PASS
#              value: password
            - name: "DB_EMBEDDED"
              value: "TRUE"
            - name: "RTP_START"
              value: "18000"
            - name: "RTP_FINISH"
              value: "18029"
          ports:
            - name: http-tcp
              containerPort: 80
              protocol: TCP
            - name: https-tcp
              containerPort: 443
              protocol: TCP
            - name: fop-tcp
              containerPort: 4445
              protocol: TCP
            - name: iax-tcp
              containerPort: 4569
              protocol: TCP
            - name: pjsip-tcp
              containerPort: 5060
              protocol: TCP
            - name: sip-tcp
              containerPort: 5160
              protocol: TCP
            - name: ucp-tcp
              containerPort: 8001
              protocol: TCP
            - name: ucp-ssl-tcp
              containerPort: 8003
              protocol: TCP
            - name: ucp2-tcp
              containerPort: 8008
              protocol: TCP
            - name: ucp2-ssl-tcp
              containerPort: 8009
              protocol: TCP
            - name: http-udp
              containerPort: 80
              protocol: UDP
            - name: https-udp
              containerPort: 443
              protocol: UDP
            - name: fop-udp
              containerPort: 4445
              protocol: UDP
            - name: iax-udp
              containerPort: 4569
              protocol: UDP
            - name: pjsip-udp
              containerPort: 5060
              protocol: UDP
            - name: sip-udp
              containerPort: 5160
              protocol: UDP
            - name: ucp-udp
              containerPort: 8001
              protocol: UDP
            - name: ucp-ssl-udp
              containerPort: 8003
              protocol: UDP
            - name: ucp2-udp
              containerPort: 8008
              protocol: UDP
            - name: ucp2-ssl-udp
              containerPort: 8009
              protocol: UDP
            {{- range untilStep 18000 18030 1 }}
            - name: rtp-{{ . }}-udp
              containerPort: {{ . }}
              protocol: UDP
            {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: asterisk-data
              mountPath: /var/log/
              subPath: var/log/
            - name: asterisk-data
              mountPath: /data
              subPath: data
            - name: asterisk-data
              mountPath: /assets/custom
              subPath: assets/custom
            - name: asterisk-data
              mountPath: /var/lib/mysql
              subPath: embedded-mysql-db
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: asterisk-data
          persistentVolumeClaim:
            claimName: asterisk-pvc
