apiVersion: v1
kind: Service
metadata:
  name: {{ include "freepbx-wes.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    helm.sh/chart: {{ include "freepbx-wes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range untilStep 18000 18030 1 }}
    - port: {{ . }}
      targetPort:  {{ . }}
      protocol: TCP
      name: rtp-{{ . }}
    {{ end }}

  selector:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
