---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  name: {{ include "freepbx-wes.fullname" . }}-voip-service-tcp
  labels:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    helm.sh/chart: {{ include "freepbx-wes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: fop-tcp
      targetPort: 4445
      port: 4445
      protocol: TCP
    - name: iax-tcp
      targetPort: 4569
      port: 4569
      protocol: TCP
    - name: pjsip-tcp
      targetPort: 5060
      port: 5060
      protocol: TCP
    - name: sip-tcp
      targetPort: 5160
      port: 5160
      protocol: TCP
    - name: ucp-tcp
      targetPort: 8001
      port: 8001
      protocol: TCP
    - name: ucp-ssl-tcp
      targetPort: 8003
      port: 8003
      protocol: TCP
    - name: ucp2-tcp
      targetPort: 8008
      port: 8008
      protocol: TCP
    - name: ucp2-ssl-tcp
      targetPort: 8009
      port: 8009
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  loadBalancerIP: 172.16.1.224

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  name: {{ include "freepbx-wes.fullname" . }}-voip-service-udp
  labels:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    helm.sh/chart: {{ include "freepbx-wes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    {{- range untilStep 18000 18030 1 }}
    - port: {{ . }}
      targetPort:  {{ . }}
      protocol: UDP
      name: rtp-{{ . }}-udp
    {{ end }}

    - name: fop-udp
      targetPort: 4445
      port: 4445
      protocol: UDP
    - name: iax-udp
      targetPort: 4569
      port: 4569
      protocol: UDP
    - name: pjsip-udp
      targetPort: 5060
      port: 5060
      protocol: UDP
    - name: sip-udp
      targetPort: 5160
      port: 5160
      protocol: UDP
    - name: ucp-udp
      targetPort: 8001
      port: 8001
      protocol: UDP
    - name: ucp-ssl-udp
      targetPort: 8003
      port: 8003
      protocol: UDP
    - name: ucp2-udp
      targetPort: 8008
      port: 8008
      protocol: UDP
    - name: ucp2-ssl-udp
      targetPort: 8009
      port: 8009
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  loadBalancerIP: 172.16.1.224
