apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  name: {{ include "freepbx-wes.fullname" . }}-voip-service
  labels:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    helm.sh/chart: {{ include "freepbx-wes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    {{- range untilStep 18000 18030 1 }}
    - port: {{ . }}
      targetPort:  {{ . }}
      protocol: UDP
      name: rtp-{{ . }}-UDP
    {{ end }}
    - name: fop-TCP
      targetPort: 4445
      port: 4445
      protocol: TCP
    - name: iax-TCP
      targetPort: 4569
      port: 4569
      protocol: TCP
    - name: pjsip-TCP
      targetPort: 5060
      port: 5060
      protocol: TCP
    - name: sip-TCP
      targetPort: 5160
      port: 5160
      protocol: TCP
    - name: ucp-TCP
      targetPort: 8001
      port: 8001
      protocol: TCP
    - name: ucp-ssl-TCP
      targetPort: 8003
      port: 8003
      protocol: TCP
    - name: ucp2-TCP
      targetPort: 8008
      port: 8008
      protocol: TCP
    - name: ucp2-ssl-TCP
      targetPort: 8009
      port: 8009
      protocol: TCP

    - name: fop-UDP
      targetPort: 4445
      port: 4445
      protocol: UDP
    - name: iax-UDP
      targetPort: 4569
      port: 4569
      protocol: UDP
    - name: pjsip-UDP
      targetPort: 5060
      port: 5060
      protocol: UDP
    - name: sip-UDP
      targetPort: 5160
      port: 5160
      protocol: UDP
    - name: ucp-UDP
      targetPort: 8001
      port: 8001
      protocol: UDP
    - name: ucp-ssl-UDP
      targetPort: 8003
      port: 8003
      protocol: UDP
    - name: ucp2-UDP
      targetPort: 8008
      port: 8008
      protocol: UDP
    - name: ucp2-ssl-UDP
      targetPort: 8009
      port: 8009
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "freepbx-wes.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  loadBalancerIP: 172.16.1.224
