# Default values for owncloud-wes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  owncloud:
    repository: owncloud/server
    tag: 10.0
  redis:
    repository: redis
    tag: 5.0
  mariadb:
    repository: mariadb
    tag: 10.3

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-wes
    kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - cloud.elastiscale.net
  tls:
    - secretName: cloud-elastiscale.net
      hosts:
        - cloud.elastiscale.net

resources: 
  owncloud: {}
  redis: {}
  mariadb: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  ceph-client: "true"

tolerations: []

affinity: {}
