apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-wes.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nexus-wes.name" . }}
    helm.sh/chart: {{ include "nexus-wes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nexus-wes.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nexus-wes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-wes-sonatype-nexus-data

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: '/nexus-data'
              name: nexus-data
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: docker
              containerPort: 5010
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 10
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 10
            initialDelaySeconds: 120
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
