{{- $fullName := include "nexus-wes.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-ing-docker
  annotations:
      kubernetes.io/ingress.class: "nginx-wes"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  rules:
    - host: nexus-jamie-docker.elastiscale.net
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 5010
  tls:
    - hosts:
      - nexus-jamie-docker.elastiscale.net
      secretName: nexus-jamie-docker-elastiscale.net
